// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5bOhmVoUTwMZOo55k3L9EyUzKOsi-g3g',
    appId: '1:24623295439:web:7f2850352dd69ce88080ba',
    messagingSenderId: '24623295439',
    projectId: 'lifeprint-36102',
    authDomain: 'lifeprint-36102.firebaseapp.com',
    storageBucket: 'lifeprint-36102.firebasestorage.app',
    measurementId: 'G-XHDFVTFJRQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCoTKBEAwdRVccWIopM60ytsHBT_c8T80s',
    appId: '1:24623295439:android:38f55759efc58cf08080ba',
    messagingSenderId: '24623295439',
    projectId: 'lifeprint-36102',
    storageBucket: 'lifeprint-36102.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAL11YNYEVOMtoghHErWADV9FZwnRpMWBE',
    appId: '1:24623295439:ios:adf3686667cc99b58080ba',
    messagingSenderId: '24623295439',
    projectId: 'lifeprint-36102',
    storageBucket: 'lifeprint-36102.firebasestorage.app',
    iosBundleId: 'com.example.lifeprint',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAL11YNYEVOMtoghHErWADV9FZwnRpMWBE',
    appId: '1:24623295439:ios:adf3686667cc99b58080ba',
    messagingSenderId: '24623295439',
    projectId: 'lifeprint-36102',
    storageBucket: 'lifeprint-36102.firebasestorage.app',
    iosBundleId: 'com.example.lifeprint',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD5bOhmVoUTwMZOo55k3L9EyUzKOsi-g3g',
    appId: '1:24623295439:web:a8b20e64687fb9578080ba',
    messagingSenderId: '24623295439',
    projectId: 'lifeprint-36102',
    authDomain: 'lifeprint-36102.firebaseapp.com',
    storageBucket: 'lifeprint-36102.firebasestorage.app',
    measurementId: 'G-R1ZY3Z05M9',
  );
}
